name: 'Matrix Git generator'
description: 'A github action that can generate a matrix to run multiple jobs from git changes'
author: 'Reyah <contact@reyah.eu>'
inputs:
  token:
    description: 'Github access token'
    required: false
    default: ${{ github.token }}
  base:
    description: |
      Git base reference, can be a branch name or a commit hash. The change list will be compared to the base.
      Will default to the last commit of the current branch
    required: false
    default: ${{ github.ref }}
  filters:
    description: A list of filter to apply
    required: true
  working_directory:
    description: Working directory to get file changes
    required: false
outputs:
  matrix:
    description: An stringified array for each sub-directories that contain a file changes and that match the filters
  empty:
    description: Return a boolean to indicate if the matrix is empty or not, useful for skipping jobs based on that matrix
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: blue
  icon: filter
